#!/usr/bin/env bash
# Validates the commit-msg hook (REQ-023, ADR-008).
# Covers: blocking behaviour, AI attribution, affirmatory language, subject length.

set -uo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/helpers/assert.sh"

HOOK="$SCRIPT_DIR/../hooks/commit-msg"
TMPFILE="$(mktemp)"
trap 'rm -f "$TMPFILE"' EXIT

run_hook() {
  local msg="$1"
  printf '%s' "$msg" > "$TMPFILE"
  bash "$HOOK" "$TMPFILE" 2>&1
  echo "$?"
}

# Returns just the exit code from the last line of run_hook output
exit_of() {
  run_hook "$1" | tail -n1
}

echo ""
echo "=== commit-msg hook — REQ-023, ADR-008 ==="

# ── Clean messages pass ───────────────────────────────────────────────────
echo ""
echo "--- Clean messages (should exit 0) ---"

code=$(exit_of "feat(auth): add JWT refresh token rotation")
assert_equals "0" "$code" "clean feat commit exits 0"

code=$(exit_of "fix(setup): skip Tier 1 tools in install_enforcement_hooks")
assert_equals "0" "$code" "clean fix commit exits 0"

code=$(exit_of "$(printf 'docs(standards): update commit-msg hook to blocking\n\nBody text is allowed.')")
assert_equals "0" "$code" "commit with body exits 0"

# ── AI attribution blocks ─────────────────────────────────────────────────
echo ""
echo "--- AI attribution (should exit 1) ---"

code=$(exit_of "$(printf 'feat(auth): add login\n\nCo-Authored-By: Claude Sonnet 4.6 <noreply@anthropic.com>')")
assert_equals "1" "$code" "Co-Authored-By Claude blocks"

code=$(exit_of "$(printf 'fix(hooks): repair gate\n\nCo-Authored-By: Copilot <copilot@github.com>')")
assert_equals "1" "$code" "Co-Authored-By Copilot blocks"

code=$(exit_of "feat(x): AI-assisted refactor")
assert_equals "1" "$code" "AI-assisted in subject blocks"

code=$(exit_of "feat(x): add feature generated by Claude")
assert_equals "1" "$code" "generated by Claude blocks"

# ── Affirmatory language blocks ───────────────────────────────────────────
echo ""
echo "--- Affirmatory language (should exit 1) ---"

code=$(exit_of "Done.")
assert_equals "1" "$code" "Done. blocks"

code=$(exit_of "Fixed!")
assert_equals "1" "$code" "Fixed! blocks"

code=$(exit_of "feat(x): working now after many attempts")
assert_equals "1" "$code" "working now blocks"

# ── Subject length blocks ─────────────────────────────────────────────────
echo ""
echo "--- Subject line length (should exit 1 when >72) ---"

SHORT="feat(scope): boundary test subject line padded to length 72!!!!!!!!!!!!!"   # verified 72 chars (bash ${#})
code=$(exit_of "$SHORT")
assert_equals "0" "$code" "72-char subject exits 0 (boundary)"

LONG="feat(scope): boundary test subject line padded to length 73!!!!!!!!!!!!!!"  # verified 73 chars (bash ${#})
code=$(exit_of "$LONG")
assert_equals "1" "$code" "73-char subject exits 1 (over limit)"

# ── Blocking message printed ──────────────────────────────────────────────
echo ""
echo "--- Block output includes guidance ---"

output=$(run_hook "$(printf 'feat(x): ok\n\nCo-Authored-By: Claude <noreply@anthropic.com>')" | sed '$d')
assert_contains "Commit blocked" "$output" "block output says 'Commit blocked'"
assert_contains "no-verify"       "$output" "block output mentions --no-verify bypass"

print_summary
